.TH yandere 1 2026-05-28 "Utils Project" "UTILS PROJECT"
.SH NAME
yandere - prints a yandere-like sentence ad infinitum
.SH SYNOPSIS
.nf
\fByandere\fR
.fi
.SH DESCRIPTION
\fByandere\fR writes a yandere-like string on \fBstdout\fR until the program termination.
.SH USAGE
Execute the program and see the console window getting covered with yandere-like strings!
.SH EXAMPLE
.B "＊ Appreciating an implementation"
.RS
.sp
$ yandere
.sp
.RE
.B "＊ Terminates the Program"
.RS
In order to terminate the program, one can press \[dq]\fBCtrl+C\fR\[dq] or invoke \[dq]\fBkill -9 $(pidof yandere)\fR\[dq].
.RE
.SH EXIT STATUS
The current specification does not mention on the exit status. Thus, the exit status is implementation-defined as of now.
.SH IMPLEMENTATIONS
Currently, \fByandere\fR has two implementations, which are all written in different languages.
.SH CONTRIBUTORS
Visit \fIhttps://github.com/sdbx/Utils/graphs/contributors\fR to see all the contributors!
.SH UTILS PROJECT
\fByandere\fR is part of the \fBUtils\fR utility suite.
For more information, please visit \fIhttps://github.com/sdbx/Utils\fR to browse the whole project.
