name: Test for heading Rust implementation
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Run test
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./test
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Build object program
        run: rustc hd.rs -C debuginfo=0 -C opt-level=z -C strip=symbols -o hd
        working-directory: ./hd/rust
      - name: Build test maker
        run: gcc -o test_maker test_maker.c
      - name: Build host program
        run: ./test_maker .test/hd.test
      - name: Run test
        run: ./test ../hd/rust/hd
        timeout-minutes: 5
