name: Test for noisy Python implementation
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Run test
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./test
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build test maker
        run: gcc -o test_maker test_maker.c
      - name: Build host program
        run: ./test_maker .test/nsy.test
      - name: Run test
        run: ./test "python3 ../nsy/python/nsy.py"
        timeout-minutes: 5
