name: Test for C implementations
on:
  pull_request:
    branches: [main]

jobs:
  prepare:
    name: Prepare test
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./test
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build test maker
        run: gcc -o test_maker test_maker.c

  test-btn:
    name: Run buntang test
    runs-on: ubuntu-22.04
    needs: prepare
    steps:
      - name: Build object program
        run: ls 2>&1 >/dev/null
      - name: Build host program
        run: ./test_maker .test/btn.test
        working-directory: ./test
      - name: Run test
        run: ./test ../btn/c/btn
        working-directory: ./test
        timeout-minutes: 5
