name: Test for Haskell implementations
on:
  pull_request:
    branches: [main]

jobs:
  prepare:
    name: Prepare test
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./test
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build test maker
        run: gcc -o test_maker test_maker.c

  test-btn:
    name: Run buntang test
    runs-on: self-hosted
    needs: prepare
    defaults:
      run:
        working-directory: ./test
    steps:
      - name: Build object program
        run: ghc btn.hs
        working-directory: ./btn/haskell
      - name: Build host program
        run: ./test_maker .test/btn.test
      - name: Run test
        run: ./test ../btn/haskell/btn
        timeout-minutes: 5

  test-hd:
    name: Run heading test
    runs-on: self-hosted
    needs: prepare
    defaults:
      run:
        working-directory: ./test
    steps:
      - name: Build object program
        run: ghc hd.hs
        working-directory: ./hd/haskell
      - name: Build host program
        run: ./test_maker .test/hd.test
      - name: Run test
        run: ./test ../hd/haskell/hd
        timeout-minutes: 5

  test-nsy:
    name: Run noisy test
    runs-on: self-hosted
    needs: prepare
    defaults:
      run:
        working-directory: ./test
    steps:
      - name: Build object program
        run: ghc nsy.hs
        working-directory: ./nsy/haskell
      - name: Build host program
        run: ./test_maker .test/nsy.test
      - name: Run test
        run: ./test ../nsy/haskell/nsy
        timeout-minutes: 5
