name: Test for C++ implementations
on:
  pull_request:
    branches: [main]

jobs:
  test:
    name: Run test
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./test
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build test maker
        run: gcc -o test_maker test_maker.c

      - name: Build object program
        run: make all
        working-directory: ./hd/cpp
      - name: Build host program
        run: ./test_maker .test/hd.test
      - name: Run test
        run: ./test ../hd/cpp/hd
        timeout-minutes: 5
