name: Test for C implementations
on:
  push:
    branches: [main]

jobs:
  test:
    name: Run test
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./test
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build test maker
        run: gcc -o test_maker test_maker.c

      - name: Build object program
        run: make all
        working-directory: ./btn/c
      - name: Build host program
        run: ./test_maker .test/btn.test
      - name: Run test
        run: ./test ../btn/c/btn
        timeout-minutes: 5

      - name: Build object program
        run: make all
        working-directory: ./hd/c
      - name: Build host program
        run: ./test_maker .test/hd.test
      - name: Run test
        run: ./test ../hd/c/hd
        timeout-minutes: 5

      - name: Build object program
        run: make all
        working-directory: ./nsy/c
      - name: Build host program
        run: ./test_maker .test/nsy.test
      - name: Run test
        run: ./test ../nsy/c/nsy
        timeout-minutes: 5
