name: Test for Python implementations
on:
  push:
    branches: [main]

jobs:
  test:
    name: Run test
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./test
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build test maker
        run: gcc -o test_maker test_maker.c

      - name: Build host program
        run: ./test_maker .test/btn.test
      - name: Run test
        run: ./test "python3 ../btn/python/btn.py"
        timeout-minutes: 5

      - name: Build host program
        run: ./test_maker .test/nsy.test
      - name: Run test
        run: ./test "python3 ../nsy/python/nsy.py"
        timeout-minutes: 5
