name: Test for C++ implementations
on:
  push:
    branches: [main]

jobs:
  prepare:
    name: Prepare test
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./test
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build test maker
        run: gcc -o test_maker test_maker.c

  test-hd:
    name: Run heading test
    runs-on: ubuntu-22.04
    needs: prepare
    defaults:
      run:
        working-directory: ./test
    steps:
      - name: Build object program
        run: make all
        working-directory: ./hd/cpp
      - name: Build test maker
        run: gcc -o test_maker test_maker.c
      - name: Run test
        run: ./test ../hd/cpp/hd
        timeout-minutes: 5
